@{
    Abstracts = "Abstract"
    Assemblies = "Assembly"
    Attributes = "Attribute"
    Alias = "TypeAccelerator"
    Aliases = "TypeAccelerator"
    Enums = "Enum"
    Exceptions = "Exception"
    Cmdlets = "Cmdlet"
    Generics = "Generic"
    Delegates = "Delegate"
    Interfaces = "Interface"
    Types = "Type"
    TypeAccelerators = "TypeAccelerator"    
    ValueTypes = "ValueType"    
}
